#!/usr/bin/env sh

RUNDIR='/mnt/space/Download/boxarts/NES Classic - Accurate USA Box Art (431 covers)/'
TNDIR='/mnt/space/Games/misc/thumbnails/Nintendo - Nintendo Entertainment Systems/Named_Boxarts/'

mv "10-Yard Fight (USA).png" "10-Yard Fight (USA, Europe).png"
mv "1942 (USA).png" "1942 (Japan, USA).png"
mv "1943 (USA).png" "1943 - The Battle of Midway (USA).png"
mv "3-D Worldrunner (USA).png" "3-D WorldRunner (USA).png"
mv "Abadox (USA).png" "Abadox - The Deadly Inner War (USA).png"
mv "A Boy and His Blob (USA).png" "David Crane's A Boy and His Blob - Trouble on Blobolonia (USA).png"
mv "Addams Family, The - Pugsley_s Scavenger Hunt (USA).png" "Addams Family, The - Pugsley's Scavenger Hunt (USA).png"
mv "Advanced D_D - DragonStrike (USA).png" "Advanced Dungeons _ Dragons - DragonStrike (USA).png"
mv "Advanced D_D - Heroes of the Lance (USA).png" "Advanced Dungeons _ Dragons - Heroes of the Lance (USA).png"
mv "Advanced D_D - Hillsfar (USA).png" "Advanced Dungeons _ Dragons - Hillsfar (USA).png"
mv "Advanced D_D - Pool of Radiance (USA).png" "Advanced Dungeons _ Dragons - Pool of Radiance (USA).png"
mv "Adventure Island 2 (USA).png" "Adventure Island II (USA).png"
mv "Adventures of Gilligan_s Island, The (USA).png" "Adventures of Gilligan's Island, The (USA).png"
mv "Adventures of Rocky and Bullwinkle, The (USA).png" "Adventures of Rocky and Bullwinkle and Friends, The (USA).png"
mv "Afterburner (USA) (Tengen Unlicensed).png" "After Burner (USA) (Unl).png"
mv "Alien Syndrome (USA) (Tengen Unlicensed).png" "Alien Syndrome (USA) (Unl).png"
mv "A Nightmare on Elm Street (USA).png" "Nightmare on Elm Street, A (USA).png"
mv "Arkista_s Ring (USA).png" "Arkista's Ring (USA).png"
mv "Bard_s Tale, The (USA).png" "Bard's Tale, The (USA).png"
mv "Baseball (USA).png" "Baseball (USA, Europe).png"
mv "Bases Loaded 2 (USA).png" "Bases Loaded II - Second Season (USA).png"
mv "Base Wars - Cyber Stadium Series (USA).png" "Cyber Stadium Series - Base Wars (USA).png"
mv "Bonk_s Adventure (USA).png" "Bonk's Adventure (USA).png"
mv "Bucky O_Hare (USA).png" "Bucky O'Hare (USA).png"
mv "Bugs Bunny - Birthday Blowout (USA).png" "Bugs Bunny Birthday Blowout, The (USA).png"
mv "Bugs Bunny - Crazy Castle (USA).png" "Bugs Bunny Crazy Castle, The (USA).png"
mv "Castlevania III (USA).png" "Castlevania III - Dracula's Curse (USA).png"
mv "Castlevania II (USA).png" "Castlevania II - Simon's Quest (USA).png"
mv "Chip n Dale Rescue Rangers 2 (USA).png" "Chip 'n Dale - Rescue Rangers 2 (USA).png"
mv "Chip n Dale Rescue Rangers (USA).png" "Chip 'n Dale - Rescue Rangers (USA).png"
mv "Clu Clu Land (USA).png" "Clu Clu Land (World).png"
mv "Codename - Viper (USA).png" "Code Name - Viper (USA).png"
mv "Digger T. Rock (USA).png" "Digger - The Legend of the Lost City (USA).png"
mv "Donkey Kong 3 (USA).png" "Donkey Kong 3 (World).png"
mv "Donkey Kong Classics (USA).png" "Donkey Kong Classics (USA, Europe).png"
mv "Donkey Kong Jr. Math (USA).png" "Donkey Kong Jr. Math (USA, Europe).png"
mv "Donkey Kong Jr. (USA).png" "Donkey Kong Jr. (World) (Rev 1).png"
mv "Donkey Kong (USA).png" "Donkey Kong (World) (Rev 1).png"
mv "Double Dragon III (USA).png" "Double Dragon III - The Sacred Stones (USA).png"
mv "Double Dragon II (USA).png" "Double Dragon II - The Revenge (USA).png"
mv "Dragon Spirit (USA).png" "Dragon Spirit - The New Legend (USA).png"
mv "Dr. Mario (USA).png" "Dr. Mario (Japan, USA).png"
mv "Dungeon Magic (USA).png" "Dungeon Magic - Sword of the Elements (USA).png"
mv "Dynowarz (USA).png" "Dynowarz - The Destruction of Spondylus (USA).png"
mv "Earthbound Zero (USA) (Custom, Unreleased).png" "EarthBound Beginnings (USA, Europe) (Virtual Console).png"
mv "Excitebike (USA).png" "Excitebike (Japan, USA).png"
mv "Fester_s Quest (USA).png" "Fester's Quest (USA).png"
mv "Fire _n Ice (USA).png" "Fire 'n Ice (USA).png"
mv "Flying Dragon (USA).png" "Flying Dragon - The Secret Scroll (USA).png"
mv "Fox_s Peter Pan and the Pirates (USA).png" "Fox's Peter Pan _ the Pirates - The Revenge of Captain Hook (USA).png"
mv "Galaga (USA).png" "Galaga - Demons of Death (USA).png"
mv "Gargoyle_s Quest II (USA).png" "Gargoyle's Quest II (USA).png"
mv "Gauntlet (USA) (Tengen Unlicensed).png" "Gauntlet (USA) (Unl).png"
mv "Ghost Lion (USA).png" "Ghost Lion (USA).png"
mv "Ghosts _n Goblins (USA).png" "Ghosts'n Goblins (USA).png"
mv "Godzilla 2 (USA).png" "Godzilla 2 - War of the Monsters (USA).png"
mv "Godzilla (USA).png" "Godzilla - Monster of Monsters! (USA).png"
mv "Gremlins 2 (USA).png" "Gremlins 2 - The New Batch (USA).png"
mv "Guardian Legend (USA).png" "Guardian Legend, The (USA).png"
mv "Heavy Shreddin_ (USA).png" "Heavy Shreddin' (USA).png"
mv "Home Alone 2 (USA).png" "Home Alone 2 - Lost in New York (USA).png"
mv "Ice Climber (USA).png" "Ice Climber (USA, Europe, Korea).png"
mv "Ikari Warriors III (USA).png" "Ikari III - The Rescue (USA).png"
mv "Ikari Warriors II (USA).png" "Ikari Warriors II - Victory Road (USA).png"
mv "Indiana Jones and the Last Crusade (USA).png" "Indiana Jones and the Last Crusade (USA).png"
mv "Indiana Jones and the Temple of Doom (USA) (Tengen Unlicensed).png" "Indiana Jones and the Temple of Doom (USA) (Unl).png"
mv "Jackie Chan_s Action Kung Fu (USA).png" "Jackie Chan's Action Kung Fu (USA).png"
mv "Jetsons, The - Cogswell_s Caper (USA).png" "Jetsons, The - Cogswell's Caper (USA).png"
mv "John Elway_s Quarterback (USA).png" "John Elway's Quarterback (USA).png"
mv "Jordan vs. Bird (USA).png" "Jordan vs Bird - One on One (USA).png"
mv "Kabuki Quantum Fighter (USA).png" "Kabuki - Quantum Fighter (USA).png"
mv "Kickmaster (USA).png" "KickMaster (USA).png"
mv "Kid Icarus (USA).png" "Kid Icarus (USA, Europe).png"
mv "Kid Klown (USA).png" "Kid Klown in Night Mayor World (USA).png"
mv "Kid Kool (USA).png" "Kid Kool and the Quest for the Seven Wonder Herbs (USA).png"
mv "King_s Knight (USA).png" "King's Knight (USA).png"
mv "King_s Quest V (USA).png" "King's Quest V (USA).png"
mv "Kirby_s Adventure (USA).png" "Kirby's Adventure (USA).png"
mv "Kiwi Kraze (USA).png" "Kiwi Kraze - A Bird-Brained Adventure! (USA).png"
mv "Krusty_s Fun House (USA).png" "Krusty's Fun House (USA).png"
mv "Kung Fu (USA).png" "Kung Fu (Japan, USA).png"
mv "Legend of Zelda, The (USA (Full Shield Graphic).png" "Legend of Zelda, The (USA).png"
rm "Legend of Zelda, The (USA) (Exposed Cart).png"
mv "Little Nemo - Dream Master (USA).png" "Little Nemo - The Dream Master (USA).png"
mv "Low G Man (USA).png" "Low G Man - The Low Gravity Man (USA).png"
mv "Mach Rider (USA).png" "Mach Rider (Japan, USA).png"
mv "Mafat Conspiracy, The - Golgo 13 (USA).png" "Golgo 13 - Top Secret Episode (USA).png"
mv "Mappyland (USA).png" "Mappy-Land (USA).png"
mv "Mario Bros. (USA).png" "Mario Bros. (World).png"
mv "M.C Kids (USA).png" "M.C. Kids (USA).png"
mv "Metal Gear II - Snake_s Revenge (USA).png" "Snake's Revenge (USA).png"
mv "MetalMech - Man _ Machine (USA).png" "MetalMech - Man _ Machine (USA).png"
mv "Metalstorm (USA).png" "Metal Storm (USA).png"
mv "Mike Tyson_s Punch Out!! (USA).png" "Mike Tyson's Punch-Out!! (Japan, USA).png"
mv "Milon_s Secret Castle (USA).png" "Milon's Secret Castle (USA).png"
mv "Monster In My Pocket (USA).png" "Monster in My Pocket (USA).png"
mv "Ms. Pac-Man (USA) (Tengen Unlicensed).png" "Ms. Pac-Man (USA) (Tengen) (Unl).png"
mv "New Ghostbusters II (USA) (Custom, Unreleased).png" "New Ghostbusters II (USA) (Proto).png"
mv "Ninja Gaiden III (USA).png" "Ninja Gaiden III - The Ancient Ship of Doom (USA).png"
mv "Ninja Gaiden II (USA).png" "Ninja Gaiden II - The Dark Sword of Chaos (USA).png"
mv "Nintendo World Championships 1990 (USA, Custom).png" "Nintendo World Championships 1990 (USA) (Competition Cart).png"
mv "Nobunaga_s Ambition II (USA).png" "Nobunaga's Ambition II (USA).png"
mv "Nobunaga_s Ambition (USA).png" "Nobunaga's Ambition (USA).png"
mv "Pac-Mania (USA) (Tengen Unlicensed).png" "Pac-Mania (USA) (Unl).png"
mv "Pinball (USA).png" "Pinball (Japan, USA).png"
mv "Popeye (USA).png" "Popeye (World) (Rev 1).png"
mv "P.O.W. (USA).png" "P.O.W. - Prisoners of War (USA).png"
mv "Puss n Boots - Pero_s Great Adventure (USA).png" "Puss 'n Boots - Pero's Great Adventure (USA).png"
mv "Qix (USA).png" "QIX (USA).png"
mv "Ren _ Stimpy Show, The - Buckeroos! (USA).png" "Ren _ Stimpy Show, The - Buckeroo$! (USA).png"
mv "Rockin_ Kats (USA).png" "Rockin' Kats (USA).png"
mv "Rolling Thunder (USA) (Tengen Unlicensed).png" "Rolling Thunder (USA) (Unl).png"
mv "Rush_n Attack (USA).png" "Rush'n Attack (USA).png"
mv "S.C.A.T. (USA).png" "S.C.A.T. - Special Cybernetic Attack Team (USA).png"
mv "Snake Rattle N Roll (USA).png" "Snake Rattle n Roll (USA).png"
mv "Snoopy_s Silly Sports Spectacular! (USA).png" "Snoopy's Silly Sports Spectacular! (USA).png"
mv "Solar Jetman - Hunt for the Golden Warship (USA).png" "Solar Jetman - Hunt for the Golden Warpship (USA).png"
mv "Solomon_s Key (USA).png" "Solomon's Key (USA).png"
mv "Solstice (USA).png" "Solstice - The Quest for the Staff of Demnos (USA).png"
mv "StarTropics II - Zoda_s Revenge (USA).png" "Zoda's Revenge - StarTropics II (USA).png"
mv "Street Fighter 2010 (USA).png" "Street Fighter 2010 - The Final Fight (USA).png"
mv "Super Mario Bros. (USA).png" "Super Mario Bros. (World) (HVC-SM).png"
mv "Target - Renegade (USA).png" "Target - Renegade (USA).png"
mv "Teenage Mutant Ninja Turtles III (USA).png" "Teenage Mutant Ninja Turtles III - The Manhattan Project (USA).png"
mv "Teenage Mutant Ninja Turtles II (USA).png" "Teenage Mutant Ninja Turtles II - The Arcade Game (USA).png"
mv "Tetris (USA) (Tengen Unlicensed).png" "Tetris (USA) (Tengen) (Unl).png"
mv "Tiny Toon Adventures 2 (USA).png" "Tiny Toon Adventures 2 - Trouble in Wackyland (USA).png"
mv "Tiny Toon Adventures - Cartoon Workshop (USA).png" "Tiny Toon Adventures Cartoon Workshop (USA).png"
mv "Toobin_ (USA) (Tengen Unlicensed).png" "Toobin' (USA) (Unl).png"
mv "Town _ Country Surf Designs - Thrilla_s Surfari (USA).png" "Town _ Country Surf Designs - Thrilla's Surfari (USA).png"
mv "Untouchables, The (USA) (Official, Variant 1).png" "Untouchables, The (USA).png"
rm "Untouchables, The (USA) (Official, Variant 2).png"
mv "Urban Champion (USA).png" "Urban Champion (World).png"
mv "Vindicators (USA) (Tengen Unlicensed).png" "Vindicators (USA) (Unl).png"
mv "Volleyball (USA).png" "Volleyball (USA, Europe).png"
mv "Wario_s Woods (USA).png" "Wario's Woods (USA).png"
mv "Wayne_s World (USA).png" "Wayne's World (USA).png"
mv "Werewolf (USA).png" "Werewolf - The Last Warrior (USA).png"
mv "Whomp _Em (USA).png" "Whomp 'Em (USA).png"
mv "Wizards _ Warriors II - Ironsword (USA).png" "IronSword - Wizards _ Warriors II (USA).png"
mv "World Champ (USA).png" "World Champ (USA).png"
mv "Wrecking Crew (USA).png" "Wrecking Crew (World).png"
mv "WURM (USA).png" "Wurm - Journey to the Center of the Earth! (USA).png"
mv "Xevious (USA).png" "Xevious - The Avenger (USA).png"
mv "Yoshi_s Cookie (USA).png" "Yoshi's Cookie (USA).png"

for fich in "${RUNDIR}"/*.png; do
  if [ ! -f "${TNDIR}/${fich}" ]; then
    echo "Still missing: $fich"
  fi
done
